config/routes.rb
Rails.application.routes.draw do
  #URLの変更
  # get '/mypage', to: 'mypage#index' # 間違ってた
  get '/mypage', to: 'mypage#show'
  # Task11-3で追加。URLの末尾＝mypage#showだよ。今回はindex.htmlで作ったので模範と少し違う
  # get "/", to: 'articles#index', as: :articles #これだとうまくDBが構築できない
  # post "/" => 'article#create'
  root to: 'articles#index'
  # root to: 'mypage#index'
  # root to: 'home#index' #Task10-1で追加したコード
  #get "(hostから後ろ)任意のURL", to: 'コントローラのメソッドで行う処理', as: (パスが入った変数？)

  devise_for :users
  # devise_for :models #いらないかなー
  # get '/articles', to: 'articles#search' as: 'search' #Task14/勘違い


  resources :articles #g scaffold --forceで作られた
  resources :mypage #Task11-3で手動で追記した
  # resources :test_tags #RESTfulな動作にするには必要。
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  # 参考サイトより追記
  belongs_to:user

  validates :title, presence: true #uniqueness: true # Task12ではバリデーションの設定はしない。
  validates :content, presence: true
  # まだテストしてない（エラーが起きたら、コメント外して）
  # def user
  #   return User.find_by(id: self.user_id)
  # end

  # Task15で追加（タグと記事の関係）
	has_many :article_tags, dependent: :destroy #article_tagとの関係も記述する
  has_many :tags, through: :article_tags #article_tag(中間)を通して、tagと紐付け

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	skip_before_action :authenticate_user!, only: %i[index show]
  # before_action :set_article, only: %i[show edit update destroy ] #Task11-1まで
  before_action :set_article, only: %i[ edit update destroy ] #Task11-2で変更

  # before_actionは何かを実行する前に行う処理
  # 下記にset_articleメソッドがある
  # onlyは処理を指定する。（skipなら「次のシンボルは無視する」ということ）
  # %iはシンボル形式に変換する。だからonly:[:show,:edit,:update,:destroy]と書いてもok
  # Task11-2:なぜbefore_actionからshowを消した？→記事を見るだけなら誰でもええやん

  #Task10で追加したコード
  # before_action :authenticate_user! #これいる？ヘルパー使う場合に使うbeforeaction→必要やった→やっぱ必要なかった→特定の条件下で必要やったw
  # before_action :authenticate_member! #これいる？ヘルパー使う場合に使うbeforeactionな気がする→必要やった。なくてもいけた
  #上がないとトップ画面でログイン画面が出てこない
  #authenticate_memberがないとDBにユーザを登録できない。上のメソッドがない？
  # でもなくても行けた。よくわからないwwww
  # 結論：authenticate_user!はログイン画面に移行するメソッド／アカウントの登録とは別。なくても動くが挙動は大きく変わるはず

  # GET /articles or /articles.json
  def index
    # @articles = Article.all #Task12まで使っていた。
    # @articles = Article.all.page(params[:page]) # Task13まで
    # search = Article.where('title LIKE ?', "%#{title}%") #あいまい検索
    # Task14で追加／タイトルのあいまい検索
    article = Article.all #articlesに全記事を代入する
    title = params[:title] #text_tagで取得したパラメータ
    # binding.pry
    article = article.where("title LIKE ?", "%#{title}%") if title.present? #if修飾子（Tの場合は処理 if 条件式）
    @articles = article.all.page(params[:page]) #ページネイションで表示する。
    # Article：DBテーブル、.all：全部。つまり、Articleテーブルのデータを全て@articleに入れる。
    # @boards = Board.all.includes(:user).order(created_at: :desc).page(params[:page]) #参考サイトのコード
    # 上記２行を合体してみた
    # @articles = Article.all.includes(:user).order(created_at: :desc).page(params[:page])
    # title=nilの場合、全部の記事を取得する。また検索ワードを入れなかったらprams[:title]はnilを返す
  end

  # GET /articles/1 or /articles/1.json
  def show
    @article = Article.find(params[:id]) #追加
    # Task11-2で追加になっているが、before_actionに組まないのはなぜか？
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    # @article = Article.new(article_params) #Task11-1まで
    # @article.user_id = current_user.id #自分で変更したコード
    @article = current_user.articles.new(article_params) # Task11-2で追加（模範）
    # binding.pry
    # respond_to do |format| #これなに？→レスポンスをフォーマットごとに変えてる。（HTML形式とJSON形式）
    if @article.save #記事が保存できるか
      # 真の場合の処理
      # binding.pry
        redirect_to @article, notice: "#{t('activerecord.models.article')}を作成しました。" #Task11-2で模範回答に調整
        # format.html { redirect_to article_url(@article), notice: "記事の作成に成功しました！" }
        # format.json { render :show, status: :created, location: @article }
      else
        render :new, status: :unprocessable_entity #模範回答
        # format.html { render :new, status: :unprocessable_entity }
        # format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    # end
    # def create #なぜこれを作ったのか覚えてない
    #   @article = Article.new(p
    #     title: params[:title],
    #     content: params[:content]
    #   )
    #   @article.save!
    #   render :show
    # end
  end

  def update
    # binding.pry
    if  @article.user_id == current_user.id #アカウントが違った場合の処理
      # respond_to do |format|
        if @article.update(article_params)
          redirect_to article_url(@article), notice: "記事を更新しました。"
          # format.html { redirect_to article_url(@article), notice: "記事を更新しました。" }
          # format.json { render :show, status: :ok, location: @article } #jsonは使わない
          # redirect_to @article, notice: "Article was successfully updated." #模範回答
          # notice:"記事を更新しました"とサイト上に表示される機能
          # fromat.html{}はhtml形式に変更する。（.htmlを.jsonにするとjson形式になる）
        else
          render :edit, status: :unprocessable_entity
          # format.html { render :edit, status: :unprocessable_entity }
          # format.json { render json: @article.errors, status: :unprocessable_entity } #jsonは使わない
          # render :edit, status: :unprocessable_entity #模範回答
        end
      # end
    else
      redirect_to article_url(@article), notice: "アカウントが違います！"
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    if  @article.user_id == current_user.id
      @article.destroy #destroyメソッドを実行する
      respond_to do |format|
        # redirect_to articles_url, notice: "Article was successfully destroyed."
        # format.html { redirect_to articles_url, notice: "記事を削除しました。" } #articles_urlはarticle#indexを開く。多分format.htmlはなくてもいける。
        format.html { redirect_to  mypage_index_url, notice: "記事を削除しました。" } #削除後にmypage_index戻るように設定
        # format.json { head :no_content } #jsonは使わないから
      end
    else
      redirect_to articles_url, notice: "垢ちゃう"
    end
  end

  # Task14で追加（検索フォームに関するメソッド／いらない）
  def search
    title = params[:title]
    # binding.pry
    # タイトルの完全一致で検索
    # @article=Article.where(title:title)
    # タイトルのあいまい検索
    @article=Article.where('title LIKE ?', "%#{title}%")
    # @article=Article.where('title LIKE ?', "%#{params[:title]}%")
    # 検索結果で見つからなかった場合の処理。
    # if Article.where(title:title).empty?
    #   puts "真"
    #   # @article = Article.all.page(params[:page])
    # else
    #   puts "偽"
    #   @article = Article.where(title:title)
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = current_user.articles.find(params[:id]) #Task11-2で追加、模範回答
      # @article = Article.find(params[:id]) #Task11-1まで
      # before_actionの後ろにset_articleがあり、ここでその処理を行ってる。
      # "Article.find(id)"でArticlesテーブルの指定したidのレコードを引っ張る
      # .findは検索メソッド
      # DBとデータをやり取りする際にparamsメソッドを使う？
      # findメソッドを使わないとエラーになるのかな？
      # params[:id]でエラーになったら、.find(params[:id])で試してみる→id参照するならfindメソッドは必要
    end

    # Only allow a list of trusted parameters through.
    # このメソッド使ってるかわからない（笑）
    def article_params
      params.require(:article).permit(:title, :content, tag_ids:[])  #Task15-2で:tagを追加した
    end
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>
      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!--Task15-2で追加-->
  <div class="mb-3">
    <%= form.collection_check_boxes :tag_ids, Tag.all, :id, :name %>
  </div>

<!--サイトではこのへんから〜-->
  <!--下記はbootstrap後に追記したコード-->
  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :content, class: "form-label" %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit '保存', class: "btn btn-primary",style:"margin:8px" %> |
    <!--link_to '戻る', article_path, class: "btn btn-secondary" %>-->
    <!--戻るボタンを押した後にmypage_indexを表示する設定-->
    <%= link_to '戻る', mypage_index_path, class: "btn btn-secondary",style:"margin:8px" %>
  </div>
<% end %>

app/views/articles/_search.html.erb
<!--Task14でファイルの追加およびテンプレートにより下記のコードを追加-->
<%= form_with url: articles_url, method: :get, local: true do |form| %>
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="mb-3">
        <%= form.label 'タイトル', class: "form-label" %>
        <%= form.text_field :title, value:params[:title], class: "form-control" %>
      </div>
      <div class="actions">
        <%= form.submit '検索', class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/edit.html.erb
<!--<h1>Editing Article</h1>-->
<h1>記事の編集</h1>

<%= render 'form', article: @article %>

<!--<%= link_to '表示', @article %> show-->
<!--<%= link_to '戻る', articles_path %> back-->

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="color:blue;">ようこそ！Wonderful post appへ</h1>
<!--Task13で追加したページネイション機能-->
<%= paginate @articles %>

<!--Task14で追加した検索-->
<%= render partial: 'search' %>

<!--Task11-2で削除／動作確認後消してみる-->
<%= link_to '記事作成', new_article_path, class: "btn btn-info" %><!--Task11-2記事作成ボタン消去-->

<table class="table">
  <thead>
    <tr>
      <th scope="col">表題：</th> <!--title-->
      <th scope="col">内容：</th><!--content-->
    </tr>
  </thead>

  <tbody>
  <!-- binding.pry%>-->
    <!--@articles.each do |article| %>@articlesの中にあるデータをeach文で表示する-->
    <% @articles.preload(:tags).each do |article| %><!--TaskEx:N+1問題の対策-->
      <tr>
        <!--Task15-2で追加した。下の行はコメントアウト-->
        <!--<td><%= article.title %></td>--><!--Task15-2でコメントアウト-->
        <td>
          <%= article.title %>
          <% article.tags.each do |tag| %>
          <!-- binding.pry %>-->
            <span class="badge rounded-pill bg-primary"><%= tag.name%></span>
          <% end %>
        </td>
        <!--.contentは記事(content)を表示するメソッド-->
        <td><%= article.content %></td>
        <td><%= link_to '表示', article, class: "btn btn-success"%>
</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/new.html.erb
<!--<h1>New Article</h1>-->
<h1>新しい記事の作成</h1>

<%= render 'form', article: @article %>
<!--<%= link_to '戻る', articles_path, class: "btn btn-secondary" %>-->

app/views/articles/search.html.erb
<!--結局これは不要だった。一回PLしてから削除する。-->
<h1>テスト表示</h1>
<tbody>
  <% @article.each do |article| %><!--@articlesの中にあるデータをeach文で表示する-->
    <tr>
      <td>
        <%= article.title %>
      </td>
      <td><!--.contentは記事(content)を表示するメソッド-->
        <%= article.content %>
      </td>
      <td>
        <%= link_to '表示', article, class: "btn btn-success"%>
      </td>
    </tr>
  <% end %>
</tbody>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card">
  <div class="card-header">
    <%= @article.title %>
    <% @article.tags.each do |tag| %>
      <span class="badge rounded-pill bg-primary"><%= tag.name%></span>
    <% end %>
    <!--<strong>タイトル:</strong>-->
  </div>

  <div class="card-body">
    <!--<strong>本文:</strong>-->
    <%= @article.content %>
  </div>
</div>
    <!-- if  @article.user_id == current_user.id %>-->
    <% if current_user.id == @article.user_id %>
      <%= link_to '編集', edit_article_path(@article), class: "btn btn-warning", style:"margin:8px"%> |
      <!-- link_to '削除', @article, class: "btn btn-danger", method: :delete, data: { confirm: '本当にホントに消していいんか？' } %> |-->
    <% end %>

<%= link_to '戻る', articles_path, class: "btn btn-secondary",style:"margin:8px"%>