config/routes.rb
Rails.application.routes.draw do
  #URLの変更
  # get '/mypage', to: 'mypage#index' # 間違ってた
  get '/mypage', to: 'mypage#show'
  # Task11-3で追加。URLの末尾＝mypage#showだよ。今回はindex.htmlで作ったので模範と少し違う
  # get "/", to: 'articles#index', as: :articles #これだとうまくDBが構築できない
  # post "/" => 'article#create'
  root to: 'articles#index'
  # root to: 'mypage#index'
  # root to: 'home#index' #Task10-1で追加したコード
  #get "(hostから後ろ)任意のURL", to: 'コントローラのメソッドで行う処理', as: (パスが入った変数？)

  devise_for :users
  # devise_for :models #いらないかなー
  # get '/articles', to: 'articles#search' as: 'search' #Task14/勘違い


  resources :articles #g scaffold --forceで作られた
  resources :mypage #Task11-3で手動で追記した
  # resources :test_tags #RESTfulな動作にするには必要。
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  def show
    # binding.pry
    # @articles = current_user.articles  # Task12まで使ってた
    # @articles = current_user.articles.page(params[:page]) # Task13で追加した（ページネイションで表示する）
    # Task14で追加したコード
    # article = current_user.articles # 
    article = current_user.articles
    title = params[:title] #text_tagで取得したパラメータ
    article = article.where('title LIKE ?', "%#{title}%") if title.present? #あいまい検索
    @articles = article.page(params[:page]) #ページネイションで表示する。
  end
end

app/views/mypage/_search.html.erb
<%= form_with url: mypage_url, method: :get, local: true do |form| %>
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="mb-3">
        <%= form.label 'タイトル', class: "form-label" %>
        <%= form.text_field :title, value: params[:title], class: "form-control" %>
      </div>
      <div class="actions">
        <%= form.submit '検索', class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/mypage/index.html.erb
<p id="notice"><%= notice %></p><!--行間開けるstyle？-->
<h1 style="color:red;">マイページビュー</h1>
<!--記事作成ボタンを配置／記事作成したらuser_idも紐づく？-->
<%= link_to '記事作成', new_article_path, class: "btn btn-info" %><!--Task11-2記事作成ボタン消去-->

<!--article/index.htmlの中身を参考にコピペ-->
<table class="table">
  <thead>
    <tr>
      <th scope="col">表題：</th>
      <th scope="col">内容：</th>
    </tr>
  </thead>
  <tbody>
   <% @articles.each do |user_article| %>
   <!-- current_user.articles.each do |user_article| %>-->
      <td><%= user_article.title %></td>
      <td><%= user_article.content %></td>
      <td><%= link_to '表示', user_article, class: "btn btn-success" %>
      <td><%= link_to '編集', edit_article_path(user_article), class: "btn btn-warning" %>
      <td><%= link_to '削除', user_article, class: "btn btn-danger", method: :delete, data: { confirm: '本当にホントに消していいんか？' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

app/views/mypage/show.html.erb
<p id="notice"><%= notice %></p><!--行間開けるstyle？-->

<h1 style="color:red;">マイページビュー</h1>
<%= render partial: "search" %><!--Task14で追加-->
<%= paginate @articles %> <!--Task13で追加-->

<!--記事作成ボタンを配置／記事作成したらuser_idも紐づく？-->
<%= link_to '記事作成', new_article_path, class: "btn btn-info" %><!--Task11-2記事作成ボタン消去-->

<!--article/index.htmlの中身を参考にコピペ-->
<table class="table">
  <thead>
    <tr>
      <th scope="col">表題：</th>
      <th scope="col">内容：</th>
    </tr>
  </thead>
  <tbody>
   <% @articles.preload(:tags).each do |user_article| %>
   <!--current_user.articles.each do |user_article| %>-->
      <!--<td><%= user_article.title %></td>-->
      <tr>
        <td>
          <%= user_article.title %>
          <% user_article.tags.each do |tag| %>
            <span class="badge rounded-pill bg-primary"><%= tag.name%></span>
          <% end %>
        </td>
        <td><%= user_article.content %></td>
        <td><%= link_to '表示', user_article, class: "btn btn-success" %></td>
        <td><%= link_to '編集', edit_article_path(user_article), class: "btn btn-warning" %></td>
        <td><%= link_to '削除', user_article, class: "btn btn-danger", method: :delete, data: { confirm: '本当にホントに消していいんか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>