config/routes.rb
Rails.application.routes.draw do
  #URLの変更
  # get '/mypage', to: 'mypage#index' # 間違ってた
  get '/mypage', to: 'mypage#show'
  # Task11-3で追加。URLの末尾＝mypage#showだよ。今回はindex.htmlで作ったので模範と少し違う
  # get "/", to: 'articles#index', as: :articles #これだとうまくDBが構築できない
  # post "/" => 'article#create'
  root to: 'articles#index'
  # root to: 'mypage#index'
  # root to: 'home#index' #Task10-1で追加したコード
  #get "(hostから後ろ)任意のURL", to: 'コントローラのメソッドで行う処理', as: (パスが入った変数？)

  devise_for :users
  # devise_for :models #いらないかなー
  # get '/articles', to: 'articles#search' as: 'search' #Task14/勘違い


  resources :articles #g scaffold --forceで作られた
  resources :mypage #Task11-3で手動で追記した
  # resources :test_tags #RESTfulな動作にするには必要。
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-light">
  <div class="container-fluid">
    <!------TOPへのリンク設置------->
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "トップ",root_path, class:"nav-link active" %>
          </li>
        <% if user_signed_in?%> <!--user_signed_inはdevicesメソッドでuserがログインしているか判断するメソッド-->
        <!--サインイン状態なら-->
          <li class="nav-item">
          <!------認証の各ボタン設置------->
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"nav-link active" %>
            <!--class:"nav-link active"はbootstrapで予め設定されたスタイル-->
            <!--***_pathとrails routesで使えるメソッドが一致する。-->
            <!--link_toはHTMLで表示される文字-->
            <!--destroy_model_session_pathはサインアウト処理行う？-->
          </li>
            <!--ログインしているユーザのアドレスを表示する-->
            <!-- binding.pry #動作確認%>-->
            <!--<li class="nav-link active"><%=link_to current_user.email, mypage_index_path%></li>-->
            <li class="nav-link active"><%=link_to current_user.email, mypage_path%></li>
            <!--<li>current_user.email, class:"nav-link active" #これはエラーになる%></li>-->
        <% else %><!--サインイン状態以外なら-->
          <li class="nav-item">
            <!------認証の各ボタン設置------->
            <%= link_to "サインアップ", new_user_registration_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <!------認証の各ボタン設置------->
            <%= link_to "サインイン", new_user_session_path, class: "nav-link active" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WonderfulPostApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> #Qiitaで追加したコード-->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>TaskEx2作業前-->
    <%=javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- javascript_include_tag 'application'%>-->
    <!--Task10で追加した-->
    <!-- javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>-->

  </head>

  <body>
    <%= render partial: "layouts/navbar" %>
    <!--views/layouts/_navbar.html.erbを読み込むのかな-->
    <!--<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>-->
    <div class="container"> <!--bootstrap導入後-->
     <%= yield %>
    </div>
  </body>
</html>